# Generated by Django 3.2.21 on 2023-09-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='avg_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
