# Generated by Django 3.2.21 on 2023-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0005_transaction_split_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price Per Share', max_digits=10, null=True),
        ),
    ]
